Add UserForm component, style, yupValidation
DmytroZhdanov/power-pulse pull request #24
Opened 2023-10-22 13:49 UTC by Tanyusha7

2023-10-22 15:00 UTC, DmytroZhdanov requested changes

2023-10-22 15:00 UTC, DmytroZhdanov commented on src/components/profile/UserForm/UserForm.styled.jsx
Горизонтальні падінги на формі потрібно прибрати. Оригінальним чекбоксам треба задати display: none, а кастомним підправити розміри та трошки стилі, бо не за макетом. Там де список чекбоксів зі стилем життя, починаючи з планшету другий рядок на одному рядку з першим. І там Паша займається теж формами але авторизації. І він зробив зміну кольору на зелений, червоний та помаранчевий як по макету. Звʼяжіться між собою аби він поділився як це зробити. Бо він добу на це витратив, а так швидше тобі розкаже і меньше часу витратиш) Плюс звʼяжись із Тарасом, аби він пояснив по компоненту BirthInput якщо будуть питання

2023-10-24 22:39 UTC, Tanyusha7 commented on src/components/profile/UserForm/UserForm.styled.jsx
Переробила стилізацію і трохи змінила структуру під стилізацію. Щодо вілідації (зміна кольору на імпутах), це подивлюся завтра.

Щодо стилізації календаря, при його відкритті вся його стилізація летить, десь перебиваються моїми стилями. Хто ним займався, хай підправить стилізацію під мою сторінку. І коли вибираю дату, вона не відображається в моєму імпуті. Функціонал календаря ще буде доопрацьовуватися? Бо в мене на сторінці він не працює.

2023-10-25 13:41 UTC, DmytroZhdanov approved these changes

2023-10-25 13:41 UTC, merged