add styles on Profile page, update styles in components UserCard and …
DmytroZhdanov/power-pulse pull request #47
Opened 2023-10-25 19:55 UTC by Tanyusha7

…FormUser, add imaje.png for avatar

2023-10-25 19:57 UTC, Tanyusha7 commented
замінила аватарку згідно з макетом, стилізувала сторінку Profile, підправила стилі в компонентах під стилізацію сторінки

2023-10-25 21:37 UTC, Tanyusha7 commented
щодо кнопок, поки що залишаю таку стилізацію

2023-10-26 04:50 UTC, DmytroZhdanov requested changes

2023-10-26 04:50 UTC, DmytroZhdanov commented on src/components/profile/UserCard/UserCard.jsx
Після відкриваючого тегу компонента Image вставляємо тернарник і робимо перевірку. Якщо в параметрах користувача немає фоток, то вставляємо всередину свг. Якщо є, тоді замість іконки рендеримо img. Фото профілю також треба реалізувати через srcset для респонсивності

2023-10-26 15:41 UTC, DmytroZhdanov approved these changes
В компоненті UserForm на кнопку save потрібно буде прописати перевірку за якою вона буде disabled. І ті стилі, що зараз прописані для неї, точніше колір слова "save", буде поточний, якщо disabled = true і звичайний світлий якщо disabled = false

2023-10-26 15:41 UTC, DmytroZhdanov commented on src/components/profile/UserCard/UserCard.jsx
> +  const [avatar, setAvatar] = useState(isAvatar ? isAvatar : null);
useSelector можна одразу вставити сюди замість тернарника. Зі стейту так чи інакше приходитиме null або обʼєкт

2023-10-26 15:41 UTC, DmytroZhdanov commented on src/components/profile/UserCard/UserCard.jsx
>    const [name, setName] = useState('Anna Rybachok');
Імʼя беремо зі стейту селектором

2023-10-26 15:41 UTC, DmytroZhdanov commented on src/components/profile/UserCard/UserCard.jsx
>    const [calories, setСalories] = useState(0);
В головній гілці вже є хук який робить запит та повертає тільки денну норму калорій useFetchDailyRateQuery

2023-10-26 15:41 UTC, DmytroZhdanov commented on src/components/profile/UserCard/UserCard.jsx
>    const [sportTime, setSportTime] = useState(0);
Денна норма часу у нас статична для всіх користувачів

2023-10-26 15:41 UTC, DmytroZhdanov commented on src/components/profile/UserCard/UserCard.jsx
> +            <img src={avatar} alt="Your avatar" />
Ось тут треба буде зробити через srcset

2023-10-26 15:44 UTC, DmytroZhdanov commented
Також потрібно взяти до уваги повідомлення в девтулзах
<img width="1470" alt="Знімок екрана 2023-10-26 о 18 43 42" src="https://github.com/DmytroZhdanov/power-pulse/assets/119117057/f634678a-9a09-4ee4-935a-112fa37f210a">

2023-10-26 15:45 UTC, merged